#!/bin/bash

# NO Setup
# Installation Setup script for Ubuntu Minimal


# Make sure only root can run our script
if [[ $EUID -ne 0 ]]; then
    echo "Installation script must be run as root"
    exit 1
fi

# CONSTANTS

# Define "user interface" width and height.
# should be small for small resolutions.
NOLIN=20
NOCOL=70
NOVIW=10

# Get the Ubuntu version
# Fx.
# DISTRIB_ID=Ubuntu
# DISTRIB_RELEASE=12.04
# DISTRIB_CODENAME=precise
# DISTRIB_DESCRIPTION="Ubuntu 12.04 LTS"
source /etc/lsb-release

# Supported ubuntu versions
supported_versions[0]='12.04'
supported_versions[1]='14.04'

# FUNCTIONS

menu_main()
{
    menu=$(whiptail\
        --title "Choose Package Installation Method"\
        --menu " " $NOLIN $NOCOL $NOVIW \
        "A)" "Default Installation.    (Recommended)"\
        "B)" "Guided Installation.     Wizard installation. "\
        "C)" "Advanced Installation.   Choose packages. "\
        3>&1 1>&2 2>&3)

    exitstatus=$?

    if [ "$exitstatus" == 1 ]; then
        exit 0
    fi

    if [ "$menu" == 'A)' ]; then
        install_default
        exit
    fi

    if [ "$menu" == 'B)' ]; then
        menu_guide
        exit
    fi

    if [ "$menu" == 'C)' ]; then
        menu_list
        exit
    fi
}


install_default()
{

    package_file=${1-packages/$DISTRIB_RELEASE/default}
    package_string=$(tr '\n' '\n' <$package_file)

    oIFS="$IFS"
    IFS="
    "
    IFS=${IFS:0:1}
    lines=( $package_string )
    package_names=()
    package_title=()

    n_lines=0

    for line in "${lines[@]}"
    do
        first=`echo ${line%% *}`
        rest=`echo ${line#* }`
        package_names+=($first)
        package_title+=($rest)
        n_lines=`expr $n_lines + 1`
    done

    echo ${package_names[@]}

    whiptail\
        --title "Default Installation"\
        --yesno "This will install with the default packages.\n Are you sure?"\
        $NOLIN $NOCOL

    exitstatus=$?

    if [ $exitstatus = 0 ]; then
        # Insert i3 to apt packages
        setup_i3

        # Update and install all other packages
        apt-get update
        apt-get -y upgrade
        apt-get -y install ${package_names[@]}
        apt-get -y install i3
    else
        menu_main
        exit
    fi

}


install_guide()
{
    # TODO Select packages
    # TODO Select package lists
    # TODO Select packages from lists (or full)

    # TODO Choose programs? (nautilus vs pcmanfm)

    exit 1
}


setup_i3()
{
    # http://i3wm.org/docs/repositories.html
    echo "deb http://debian.sur5r.net/i3/ $DISTRIB_CODENAME universe" >> /etc/apt/sources.list
    apt-get update
    apt-get --allow-unauthenticated install sur5r-keyring
}


# START PROMPT

whiptail \
 --title "No Setup"\
 --msgbox "\
\n NOTE FROM AUTHOR(S):\
\n \
\n We hope this helps! \
\n \
\n If you find any bugs, please report it on github:\
\n http://github.com/charnley/no-setup" $NOLIN $NOCOL

# Check Ubuntu Version
if ! [[ ${supported_versions[*]} =~ "$DISTRIB_RELEASE" ]]
then
    echo "Ubuntu version not supported"
    exit 1
fi

# START USER EXPERINCE

menu_main

